name: Build

on:
  push:
    branches:
      - master
    tags:
      - '*'
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/build*.yml"
      - "docker/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.23.5

      - name: Run tests
        run: go test -cover ./...

      - name: Build
        run: sh scripts/build.sh

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: release/

  docker-build:
    runs-on: ubuntu-latest
    needs: build
    env:
      PLATFORMS: linux/amd64,linux/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            nginxui/drone-runner-docker
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: release
          path: ./release

      - name: Prepare Artifacts
        run: chmod +x ./release/*/**/drone-runner-docker

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
